### ISSUE TITLE
How to create a 32bitRLE .tga 3D Object?

### ISSUE THREAD

**Issue by bofinbabu** [ProjectAsura/D3D12_Texture#1]
Thanks for your tutorial. 
How can I make my own 3D object, like the one used in this example.

**Comment by ProjectAsura** [comment]
32bitRLE.tga is not a 3D object, but 2D image file. 
To create TGA file, I use image generation tool.
For instance, "Photoshop", "Gimp", "Irfanview",  and so on.
If you want to use 3D object file in a program, please see the "D3D12_PMD" example.

**Comment by bofinbabu** [comment]
Thanks again.
What should I do if I want to load other 2d image files (say .png) instead of .tga file.
What all things I should be worried about? Which all functions I will have to modify?

**Comment by ProjectAsura** [comment]
If you want to use png file, you have to implement "PNG file loader" yourself, and replace of "asdxResTGA.h/.cpp" with your loader, and built-in it example program. Other image format versa.
I recommend you that you see article of "How to : Initialize  a Texture From a File (https://msdn.microsoft.com/ja-jp/library/windows/desktop/ff476904(v=vs.85).aspx)".

**Comment by ProjectAsura** [comment]
質問に返答済みで，その後反応がないので解決済みとみなし，チケットを閉じます。

**Comment by ProjectAsura** [comment]
ここは質問部屋じゃなくて，
バグ報告の場なので次からはメール等でお願いします。
